<?xml version="1.0"?>
<!DOCTYPE collection [
<!ELEMENT collection (description,recipe*)>
<!ELEMENT description ANY>
<!ELEMENT recipe (title,ingredient*,preparation,comment?,nutrition)> 
<!ELEMENT title (#PCDATA)>
<!ELEMENT ingredient (ingredient*,preparation)?> 
<!ATTLIST ingredient name CDATA #REQUIRED
                     amount CDATA #IMPLIED
                     unit CDATA #IMPLIED>
<!ELEMENT preparation (step*)>
<!ELEMENT step (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT nutrition EMPTY>
<!ATTLIST nutrition protein CDATA #REQUIRED
                    carbohydrates CDATA #REQUIRED
                    fat CDATA #REQUIRED
                    calories CDATA #REQUIRED
                    alcohol CDATA #IMPLIED>
]>

<collection>
	<description>
		<title>pizza</title>
	</description>
	<recipe>
		<title>something</title>
		<ingredient name="candy" amount="100g" unit="1 sever">
			<ingredient name="sugar" amount="10g" unit="2 sever">
				<preparation>
					<step>preheat the oven</step>
					<step>bake 20 minutes</step>
				</preparation>
			</ingredient>
			<preparation>
				<step>wash it</step>
				<step>stir 25 minutes</step>
				<step>cool 10 minutes</step>
			</preparation>
		</ingredient>
		<preparation>
			<step>mix</step>
		</preparation>
		<comment>Yummy</comment>
		<nutrition protein="non" carbohydrates="good" fat="0" calories="500" alcohol="red wine" />
		
	</recipe>
</collection>